# Generated by Django 3.1.1 on 2020-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('ADDRESS', models.CharField(max_length=50)),
                ('ACCTYPE', models.CharField(max_length=50)),
                ('PAN_NO', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AccDetails',
                'verbose_name_plural': 'AccDetailss',
            },
        ),
    ]
