# Generated by Django 3.1.1 on 2020-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SALARY', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tranier_info',
                'verbose_name_plural': 'Tranier_infos',
            },
        ),
    ]
